pipeline{
    agent any

    tools {
    maven 'Test Maven'
    }

    parameters {
        choice choices: ['Dev', 'Prod'], name: 'Environment'
    }

    stages {
        stage('build') {
            steps{ 
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('test') {

            parallel{
                stage('unit test'){
                    steps{
                        echo 'running unit test'
                        sh 'mvn test'
                    }
                }
                stage('integration test'){
                    steps{
                        echo 'running integration test'
                        sh 'mvn test'
                    }
                }
            }

             post {
                success {
                    //archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                    dir('target'){
                        stash name: 'maven-build', includes: '*.jar'
                    }
                }
                failure {
                    echo 'build failed'
                }
            }
        }
        stage('deploy_dev') {
            when {
                expression {
                    params.Environment == 'Prod'
                }
                beforeAgent true
            }
            steps{
                dir('target'){
                    unstash 'maven-build'
                }
            }
                
        }
        
    }
}