pipeline{
    agent any
    stages {
        stage('build') {
            steps{ 
                sh 'mvn -B -DskipTests clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
                }
                failure {
                    echo 'build failed'
                }
            }
        }
        stage('test') {
            steps{
                echo 'testing the application'
            }
        }
        stage('deploy') {
            steps{
                echo 'deploying the application'
            }
        }
        
    }
}