pipeline{
    agent any

    tools {
    maven 'Test Maven'
    }

    parameters {
        choice choices: ['Dev', 'Prod'], name: 'Environment'
    }

    stages {
        stage('build') {
            steps{ 

                script{
                    file = load 'script.groovy'
                    file.hello()
                }
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('test') {

            parallel{
                stage('unit test'){
                    steps{
                        echo 'running unit test'
                        sh 'mvn test'
                    }
                }
                stage('integration test'){
                    steps{
                        echo 'running integration test'
                        sh 'mvn test'
                    }
                }
            }

             post {
                success {
                    //archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                    dir('target'){
                        stash name: 'maven-build', includes: '*.jar'
                    }
                }
                failure {
                    echo 'build failed'
                }
            }
        }

        stage('deploy_Dev') {
            when {
                // expression {
                //     params.Environment == 'Dev'
                // }
                beforeAgent true

                branch 'develop'
            }
            steps{
                dir('target'){
                    unstash 'maven-build'
                }

            }
                
        }

        stage('deploy_Prod') {
            when {
                // expression {
                //     params.Environment == 'Prod'
                // }
                beforeAgent true

                branch 'main'
            }
            steps{

                timeout(time: 3, unit: 'DAYS') {
                    input message: 'Are you sure you want to deploy to Prod?', ok: 'Yes', submitter: 'admin'
                }
                dir('target'){
                    unstash 'maven-build'
                }

            }
                
        }
        
    }
}